# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test-build-units:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install terraform dependencies
          command: chmod +x build/* && echo '\033[B' '\r' | build/install
      - run:
          name: Setup terraform dependencies
          command: build/setup
  test-build-whole:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run terraform build/*
          command: build/run

workflows:
  test:
    jobs:
      - test-build-units
      - test-build-whole