# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build-unittest-azure:
    docker:
      - image: cimg/base:stable
        user: root
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: |
            echo '\033[B' '\r' | . build/install.sh
            . ${HOME}/.bashrc
      - run:
          name: Setup project dependencies
          command: |
            . build/setup.sh
            . ${HOME}/.bashrc
  build-intgtest-azure:
    docker:
      - image: cimg/base:stable
        user: root
    steps:
      - checkout
      - run:
          name: Run terraform build/*
          command: |
            echo '\033[B' '\r' | . build/compile.sh 
            . build/run.sh

workflows:
  unittest:
    jobs:
      - build-unittest-azure
  intgtest:
    jobs:
      - build-intgtest-azure