# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build-unittest-azure:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: |
            echo '\033[B' '\r' | build/install
            source build/install
      - run:
          name: Setup project dependencies
          command: build/setup
  # build-intg-azure:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run terraform build/*
  #         command: |
  #           build/run

workflows:
  test:
    jobs:
      - build-unittest-azure
      # - build-intgtest-azure